public class Sixty_9 {
    public static void main(String[] args) {
        byte b = 1;
        char c = 'a';
        short s = 1;
        int i = 1;
        long l = 1L;
        float f = 1.0f;
        double d = 1.0d;
        boolean bool = false;
        Byte B = 2;
        Character C = 'b';
        Short S = 2;
        Integer I = 2;
        Long L = 2L;
        Float F = 2.0f;
        Double D = 2.0d;
        Boolean BOOL = true;
        b = B;
        c = C;
        s = S;
        i = I;
        l = L;
        f = F;
        d = D;
        bool = BOOL;
        System.out.println(b);
        System.out.println(c);
        System.out.println(s);
        System.out.println(i);
        System.out.println(l);
        System.out.println(f);
        System.out.println(d);
        System.out.println(bool);
        b = 1;
        c = 'a';
        s = 1;
        i = 1;
        l = 1L;
        f = 1.0f;
        d = 1.0d;
        bool = false;
        B = b;
        C = c;
        S = s;
        I = i;
        L = l;
        F = f;
        D = d;
        BOOL = bool;
        System.out.println(B);
        System.out.println(C);
        System.out.println(S);
        System.out.println(I);
        System.out.println(L);
        System.out.println(F);
        System.out.println(D);
        System.out.println(BOOL);
    }
}
